(() => {
  const series = [
    {
      metric: "resolved",
      category: "tickets",
      entries: [
        ["🎟️", "warm_queue", "Queue Warmer", "Close 10 tickets. The queue has learned your name.", 10],
        ["📨", "reply_expected", "Reply Expected", "Close 50 tickets. Users now assume you live inside Outlook.", 50],
        ["🧾", "paperwork_apprentice", "Paperwork Apprentice", "Close 250 tickets without resolving the root cause.", 250],
        ["🏅", "thousand_yard_inbox", "Thousand-Yard Inbox", "Close 1,000 tickets. Your scroll wheel requests leave.", 1000],
        ["🗃️", "filing_cabinet_soul", "Filing Cabinet Soul", "Close 5,000 tickets. Your personality is now searchable.", 5000],
        ["🎖️", "closure_consultant", "Closure Consultant", "Close 25,000 tickets and recommend a closure workshop.", 25000],
        ["🏆", "six_figure_sla", "Six-Figure SLA", "Close 100,000 tickets. Management calls it sustainable.", 100000],
        ["📜", "certified_queue_reducer", "Certified Queue Reducer", "Close 500,000 tickets. Certificate excludes printer support.", 500000],
        ["🥈", "two_million_mouse_clicks", "Two Million Mouse Clicks", "Close 2,000,000 tickets. Ergonomics has opened a ticket.", 2000000],
        ["🥇", "ten_million_closures", "Ten Million Closures", "Close 10,000,000 tickets. None were the duplicate.", 10000000],
        ["🪪", "licensed_ticket_mill", "Licensed Ticket Mill", "Close 50,000,000 tickets under an approved operating model.", 50000000],
        ["🏛️", "ministry_of_resolution", "Ministry of Resolution", "Close 250,000,000 tickets. Forms are available by ticket.", 250000000],
        ["🌐", "billion_user_support", "Billion-User Support", "Close 1,000,000,000 tickets. Somehow all users are Kevin.", 1000000000],
        ["🛰️", "planetary_service_desk", "Planetary Service Desk", "Close 5,000,000,000 tickets across three time zones and Mars.", 5000000000],
        ["👑", "queue_monarch", "Queue Monarch", "Close 25,000,000,000 tickets. The backlog bows politely.", 25000000000],
        ["🗿", "century_of_service", "Century of Service", "Close 100,000,000,000 tickets. Carbon dating confirms the runbook.", 100000000000],
        ["🌌", "galactic_case_manager", "Galactic Case Manager", "Close 500,000,000,000 tickets. Escalations now require hyperspace.", 500000000000],
        ["🔭", "trillion_ticket_telescope", "Trillion-Ticket Telescope", "Close 2,500,000,000,000 tickets and finally see the queue's end. It moved.", 2500000000000],
        ["💫", "ten_trillion_triage", "Ten-Trillion Triage", "Close 10,000,000,000,000 tickets. Priority remains Normal.", 10000000000000],
        ["♾️", "queue_heat_death", "Queue Heat Death", "Close 100,000,000,000,000 tickets. Entropy has accepted the workaround.", 100000000000000],
      ],
    },
    {
      metric: "manualClicks",
      category: "clicking",
      entries: [
        ["🖱️", "mouse_orientation", "Mouse Orientation Complete", "Click 10 times. Training marked complete automatically.", 10],
        ["👆", "index_finger_on_call", "Index Finger On-Call", "Click 25 times without claiming overtime.", 25],
        ["🫳", "manual_workaround", "Manual Workaround", "Click 50 times. Automation is in next quarter's roadmap.", 50],
        ["📎", "click_here_to_continue", "Click Here to Continue", "Click 100 times. The button was not decorative.", 100],
        ["🩹", "human_hotfix", "Human Hotfix", "Click 250 times and become part of the deployment pipeline.", 250],
        ["⌨️", "keyboard_optional", "Keyboard Optional", "Click 500 times. Written communication is now deprecated.", 500],
        ["🥉", "one_thousand_click_stare", "One-Thousand-Click Stare", "Click 1,000 times. The mouse has stopped making eye contact.", 1000],
        ["🧠", "muscle_memory_admin", "Muscle-Memory Administrator", "Click 2,500 times. Your hand knows the SLA better than you.", 2500],
        ["🛎️", "service_bell_engineer", "Service Bell Engineer", "Click 5,000 times. Every ding creates another stakeholder.", 5000],
        ["🏅", "ten_thousand_taps", "Ten Thousand Taps", "Click 10,000 times. Accessibility would like a meeting.", 10000],
        ["🦾", "procurement_denied_robot_arm", "Procurement-Denied Robot Arm", "Click 25,000 times using the approved organic actuator.", 25000],
        ["🎖️", "clickops_professional", "ClickOps Professional", "Click 50,000 times. Infrastructure as Fingers is production-ready.", 50000],
        ["🖲️", "legacy_input_specialist", "Legacy Input Specialist", "Click 100,000 times. The trackball team salutes you.", 100000],
        ["🧤", "carpal_tunnel_change_request", "Carpal Tunnel Change Request", "Click 250,000 times. Medical approval is pending CAB.", 250000],
        ["📜", "certified_button_operator", "Certified Button Operator", "Click 500,000 times. Renewal requires 40 training clicks.", 500000],
        ["🏆", "million_click_methodology", "Million-Click Methodology", "Click 1,000,000 times and publish the framework.", 1000000],
        ["🧬", "mouse_dna", "Mouse DNA", "Click 2,500,000 times. Your genome now includes left-button support.", 2500000],
        ["⚙️", "biological_automation", "Biological Automation", "Click 5,000,000 times. The machine is you.", 5000000],
        ["🪦", "mouse_warranty_voided", "Mouse Warranty Voided", "Click 10,000,000 times. Failure classified as enthusiastic use.", 10000000],
        ["👑", "supreme_click_commander", "Supreme Click Commander", "Click 25,000,000 times. Delegation remains unavailable.", 25000000],
      ],
    },
    {
      metric: "tps",
      category: "automation",
      entries: [
        ["⚙️", "cron_has_awakened", "Cron Has Awakened", "Reach 1 ticket per second. It runs on your machine.", 1],
        ["🤖", "tiny_automation", "Tiny Automation", "Reach 5 tickets per second. It has no logging by design.", 5],
        ["🔧", "script_with_confidence", "Script With Confidence", "Reach 25 tickets per second. Error handling is a future enhancement.", 25],
        ["📟", "pager_replacement", "Pager Replacement", "Reach 100 tickets per second. The pager now pages the script.", 100],
        ["🦿", "robotic_process_guessing", "Robotic Process Guessing", "Reach 500 tickets per second with approximate requirements.", 500],
        ["🧪", "automation_in_production", "Automation in Production", "Reach 2,500 tickets per second. Testing begins Monday.", 2500],
        ["🏭", "ticket_factory", "Ticket Factory", "Reach 10,000 tickets per second. Raw material is user confusion.", 10000],
        ["📈", "synergy_per_second", "Synergy per Second", "Reach 50,000 tickets per second. Finance requests a dashboard.", 50000],
        ["🚂", "runaway_runbook", "Runaway Runbook", "Reach 250,000 tickets per second. Nobody remembers the stop command.", 250000],
        ["🏅", "million_tps_club", "Million TPS Club", "Reach 1,000,000 tickets per second. Meetings remain manual.", 1000000],
        ["🛰️", "orbital_autoclose", "Orbital Auto-Close", "Reach 5,000,000 tickets per second. Latency is mostly atmospheric.", 5000000],
        ["🎛️", "control_plane_overachiever", "Control Plane Overachiever", "Reach 25,000,000 tickets per second. The data plane feels judged.", 25000000],
        ["📜", "certified_unattended_process", "Certified Unattended Process", "Reach 100,000,000 tickets per second. Annual supervision waived.", 100000000],
        ["🧠", "machine_learning_the_queue", "Machine Learning the Queue", "Reach 500,000,000 tickets per second. It learned to close Won't Fix.", 500000000],
        ["🌍", "follow_the_sun_automation", "Follow-the-Sun Automation", "Reach 2,500,000,000 tickets per second. Payroll may finally sleep.", 2500000000],
        ["🏆", "ten_billion_background_jobs", "Ten Billion Background Jobs", "Reach 10,000,000,000 tickets per second. One is still stuck.", 10000000000],
        ["🪐", "saturn_service_manager", "Saturn Service Manager", "Reach 50,000,000,000 tickets per second. Rings indicate loading.", 50000000000],
        ["⚡", "quarter_trillion_throughput", "Quarter-Trillion Throughput", "Reach 250,000,000,000 tickets per second. The network graph is now solid.", 250000000000],
        ["🌌", "trillion_tps_tenant", "Trillion-TPS Tenant", "Reach 1,000,000,000,000 tickets per second on the shared plan.", 1000000000000],
        ["♾️", "automation_all_the_way_down", "Automation All the Way Down", "Reach 10,000,000,000,000 tickets per second. The automation automates itself.", 10000000000000],
      ],
    },
    {
      metric: "clickPower",
      category: "clicking",
      entries: [
        ["💪", "firm_click", "Firm Click", "Resolve 2 tickets per click. Apply reasonable pressure.", 2],
        ["🪄", "minor_mouse_magic", "Minor Mouse Magic", "Resolve 5 tickets per click. No change record required.", 5],
        ["🔨", "percussive_resolution", "Percussive Resolution", "Resolve 10 tickets per click. Hit Apply until morale improves.", 10],
        ["🧰", "tool_assisted_clicking", "Tool-Assisted Clicking", "Resolve 25 tickets per click. The tool is another finger.", 25],
        ["🎯", "precision_bulk_close", "Precision Bulk Close", "Resolve 50 tickets per click and miss only the important one.", 50],
        ["🦸", "superuser_finger", "Superuser Finger", "Resolve 100 tickets per click. Least privilege has left the chat.", 100],
        ["🧨", "one_click_change_window", "One-Click Change Window", "Resolve 250 tickets per click. Rollback plan: click again.", 250],
        ["⚡", "high_voltage_mouse", "High-Voltage Mouse", "Resolve 500 tickets per click. USB power budget exceeded.", 500],
        ["🥉", "thousand_ticket_thumb", "Thousand-Ticket Thumb", "Resolve 1,000 tickets per click. Thumbs-up now closes incidents.", 1000],
        ["📦", "bulk_action_enthusiast", "Bulk Action Enthusiast", "Resolve 5,000 tickets per click. Selection criteria: yes.", 5000],
        ["🏅", "ten_thousand_ticket_button", "Ten-Thousand-Ticket Button", "Resolve 10,000 tickets per click. Label still says Submit.", 10000],
        ["🛠️", "industrial_mouse_driver", "Industrial Mouse Driver", "Resolve 50,000 tickets per click under heavy machinery rules.", 50000],
        ["🎖️", "hundred_thousand_handshake", "Hundred-Thousand Handshake", "Resolve 100,000 tickets per click. TCP is impressed.", 100000],
        ["🚀", "quarter_million_launch_button", "Quarter-Million Launch Button", "Resolve 250,000 tickets per click. Launch approval was implied.", 250000],
        ["📜", "certified_mass_closer", "Certified Mass Closer", "Resolve 1,000,000 tickets per click. Audit sample size: one.", 1000000],
        ["🏆", "five_million_finger", "Five-Million Finger", "Resolve 5,000,000 tickets per click. Point carefully.", 5000000],
        ["🛰️", "orbital_click_cannon", "Orbital Click Cannon", "Resolve 25,000,000 tickets per click. Accuracy is region-based.", 25000000],
        ["☄️", "impact_driven_support", "Impact-Driven Support", "Resolve 100,000,000 tickets per click. Impact is literal.", 100000000],
        ["🌠", "billion_ticket_gesture", "Billion-Ticket Gesture", "Resolve 1,000,000,000 tickets per click with one executive gesture.", 1000000000],
        ["👑", "finger_of_final_approval", "Finger of Final Approval", "Resolve 10,000,000,000 tickets per click. CAB has been bypassed by destiny.", 10000000000],
      ],
    },
    {
      metric: "upgradesOwned",
      category: "procurement",
      entries: [
        ["🛒", "first_purchase_order", "First Purchase Order", "Own 1 upgrade. Procurement has opened twelve forms.", 1],
        ["🧾", "receipt_retention", "Receipt Retention", "Own 3 upgrades and retain evidence until the sun expires.", 3],
        ["📦", "five_boxes_no_labels", "Five Boxes, No Labels", "Own 5 upgrades. Asset tags are on backorder.", 5],
        ["🗄️", "supply_closet_architect", "Supply Closet Architect", "Own 10 upgrades. The fire exit is technically visible.", 10],
        ["🪑", "ergonomic_exception", "Ergonomic Exception", "Own 15 upgrades after three occupational assessments.", 15],
        ["☕", "capitalized_coffee", "Capitalized Coffee", "Own 25 upgrades. The espresso machine is now infrastructure.", 25],
        ["🖨️", "fleet_of_printers", "Fleet of Printers", "Own 40 upgrades. None use the same toner.", 40],
        ["🔌", "dongle_diversification", "Dongle Diversification", "Own 60 upgrades across every incompatible standard.", 60],
        ["📊", "procurement_dashboard", "Procurement Dashboard", "Own 85 upgrades. Purchasing now has purchasing KPIs.", 85],
        ["🏅", "hundred_assets_no_owner", "Hundred Assets, No Owner", "Own 120 upgrades. CMDB confidence is 14%.", 120],
        ["🚚", "loading_dock_stakeholder", "Loading Dock Stakeholder", "Own 170 upgrades. Delivery is blocked by a calendar invite.", 170],
        ["🏢", "office_furniture_cloud", "Office Furniture Cloud", "Own 240 upgrades. Chairs are billed per active user.", 240],
        ["🧮", "depreciation_enjoyer", "Depreciation Enjoyer", "Own 330 upgrades and explain useful life to a keyboard.", 330],
        ["📜", "certified_purchase_whisperer", "Certified Purchase Whisperer", "Own 450 upgrades. Vendors answer before you call.", 450],
        ["🏗️", "procurement_industrial_complex", "Procurement Industrial Complex", "Own 600 upgrades. Buying requires its own platform team.", 600],
        ["🎖️", "eight_hundred_approvals", "Eight Hundred Approvals", "Own 800 upgrades. Every approver is on leave.", 800],
        ["🛳️", "container_load_of_dongles", "Container Load of Dongles", "Own 1,050 upgrades. Customs requests the business case.", 1050],
        ["🏆", "fourteen_hundred_assets", "Fourteen Hundred Assets", "Own 1,400 upgrades. Inventory spreadsheet reaches column ZZ.", 1400],
        ["🏭", "enterprise_buying_machine", "Enterprise Buying Machine", "Own 1,800 upgrades. Savings are measured against list price.", 1800],
        ["👑", "supreme_budget_consumer", "Supreme Budget Consumer", "Own 2,500 upgrades. Finance has switched to read-only mode.", 2500],
      ],
    },
    {
      metric: "distinctUpgrades",
      category: "procurement",
      entries: [
        ["🧩", "two_vendor_strategy", "Two-Vendor Strategy", "Own 2 different upgrades. Integration is now inevitable.", 2],
        ["🔀", "four_ways_to_login", "Four Ways to Log In", "Own 4 different upgrades. SSO remains aspirational.", 4],
        ["🧰", "toolbox_without_manuals", "Toolbox Without Manuals", "Own 6 different upgrades and one shared password.", 6],
        ["📚", "eight_admin_portals", "Eight Admin Portals", "Own 8 different upgrades. Bookmarks are the control plane.", 8],
        ["🕸️", "ten_vendor_web", "Ten-Vendor Web", "Own 10 different upgrades. Every outage has plausible deniability.", 10],
        ["📋", "twelve_renewal_dates", "Twelve Renewal Dates", "Own 12 different upgrades. Eleven renew automatically.", 12],
        ["🧑‍💼", "vendor_manager_spawned", "Vendor Manager Spawned", "Own 15 different upgrades. A new job title appears.", 15],
        ["🔐", "eighteen_service_accounts", "Eighteen Service Accounts", "Own 18 different upgrades. Password rotation is conceptual.", 18],
        ["🧬", "stack_diversity_program", "Stack Diversity Program", "Own 21 different upgrades that solve fourteen problems.", 21],
        ["🧭", "architecture_by_invoice", "Architecture by Invoice", "Own 24 different upgrades. The roadmap follows renewal dates.", 24],
        ["🏅", "twenty_seven_throat_to_choke", "Twenty-Seven Throats to Choke", "Own 27 different upgrades. Support ownership is highly available.", 27],
        ["🧱", "thirty_layer_platform", "Thirty-Layer Platform", "Own 30 different upgrades. Each removes one layer of simplicity.", 30],
        ["📜", "certified_stack_curator", "Certified Stack Curator", "Own 33 different upgrades. Rationalization workshop scheduled.", 33],
        ["🛰️", "thirty_six_status_pages", "Thirty-Six Status Pages", "Own 36 different upgrades. All are green during the outage.", 36],
        ["🎛️", "thirty_nine_control_planes", "Thirty-Nine Control Planes", "Own 39 different upgrades. Control remains elsewhere.", 39],
        ["🎖️", "forty_two_answers", "Forty-Two Answers", "Own 42 different upgrades. The question was interoperability.", 42],
        ["🏢", "enterprise_architecture_bingo", "Enterprise Architecture Bingo", "Own 45 different upgrades and complete every square.", 45],
        ["🌐", "fifty_single_panes", "Fifty Single Panes of Glass", "Own 50 different upgrades. You need a wall.", 50],
        ["🏆", "almost_everything_platform", "Almost-Everything Platform", "Own 55 different upgrades. Five are named Unified.", 55],
        ["👑", "full_catalog_survivor", "Full Catalog Survivor", "Own all 59 different upgrades. Procurement declares victory.", 59],
      ],
    },
    {
      metric: "spent",
      category: "procurement",
      entries: [
        ["💸", "petty_cash_pioneer", "Petty Cash Pioneer", "Spend 25 tickets. Receipt photographed at an angle.", 25],
        ["🧾", "expense_report_hero", "Expense Report Hero", "Spend 100 tickets and select Other as the cost center.", 100],
        ["💳", "corporate_card_warmup", "Corporate Card Warm-Up", "Spend 500 tickets. Fraud detection sends congratulations.", 500],
        ["📑", "three_quote_theatre", "Three-Quote Theatre", "Spend 2,500 tickets after comparing identical resellers.", 2500],
        ["🪙", "budget_dust", "Budget Dust", "Spend 10,000 tickets before Finance sweeps the account.", 10000],
        ["🏷️", "enterprise_discount", "Enterprise Discount", "Spend 50,000 tickets to save 3% against an invented price.", 50000],
        ["📈", "cost_optimization_growth", "Cost-Optimization Growth", "Spend 250,000 tickets on reducing spend.", 250000],
        ["🏅", "million_ticket_invoice", "Million-Ticket Invoice", "Spend 1,000,000 tickets. Payment terms are Net Eventually.", 1000000],
        ["🧮", "spreadsheet_capex", "Spreadsheet CAPEX", "Spend 5,000,000 tickets. Formula ownership is unclear.", 5000000],
        ["🏦", "finance_escalation", "Finance Escalation", "Spend 25,000,000 tickets. The CFO joins the incident call.", 25000000],
        ["📜", "certified_budget_absorber", "Certified Budget Absorber", "Spend 100,000,000 tickets before year-end.", 100000000],
        ["🚛", "truckload_of_licenses", "Truckload of Licenses", "Spend 500,000,000 tickets on software delivered by email.", 500000000],
        ["🏢", "strategic_vendor_dependency", "Strategic Vendor Dependency", "Spend 2,500,000,000 tickets. Exit plan is a slide.", 2500000000],
        ["🎖️", "ten_billion_business_case", "Ten-Billion Business Case", "Spend 10,000,000,000 tickets. Benefits remain qualitative.", 10000000000],
        ["🛰️", "cloud_bill_weather_system", "Cloud Bill Weather System", "Spend 50,000,000,000 tickets. Forecast says increasing.", 50000000000],
        ["🏆", "quarter_trillion_renewal", "Quarter-Trillion Renewal", "Spend 250,000,000,000 tickets. Cancellation link expired.", 250000000000],
        ["🌍", "global_budget_sink", "Global Budget Sink", "Spend 1,000,000,000,000 tickets across every region.", 1000000000000],
        ["🪐", "five_trillion_finops", "Five-Trillion FinOps", "Spend 5,000,000,000,000 tickets explaining unit economics.", 5000000000000],
        ["👑", "twenty_five_trillion_exception", "Twenty-Five-Trillion Exception", "Spend 25,000,000,000,000 tickets under emergency authority.", 25000000000000],
        ["♾️", "budget_is_a_social_construct", "Budget Is a Social Construct", "Spend 100,000,000,000,000 tickets. Finance has become philosophy.", 100000000000000],
      ],
    },
    {
      metric: "incidentsTriggered",
      category: "operations",
      entries: [
        ["🚨", "first_alarm", "First Alarm", "Survive 1 incident. It was only Sev 1 emotionally.", 1],
        ["📣", "war_room_invited", "War Room Invited", "Survive 2 incidents and receive a meeting link.", 2],
        ["🔥", "three_alarm_helpdesk", "Three-Alarm Helpdesk", "Survive 3 incidents. Catering remains unapproved.", 3],
        ["🧯", "extinguisher_familiarity", "Extinguisher Familiarity", "Survive 5 incidents. Root cause: combustible roadmap.", 5],
        ["☎️", "bridge_call_regular", "Bridge Call Regular", "Survive 8 incidents. You know the hold music.", 8],
        ["📝", "timeline_transcriber", "Timeline Transcriber", "Survive 12 incidents and record when everyone joined.", 12],
        ["🪖", "incident_veteran", "Incident Veteran", "Survive 18 incidents. Normal operations feel suspicious.", 18],
        ["🏅", "twenty_five_postmortems", "Twenty-Five Postmortems", "Survive 25 incidents. Actions are 80% overdue.", 25],
        ["🔦", "dark_mode_commander", "Dark-Mode Commander", "Survive 35 incidents, mostly after sunset.", 35],
        ["🎖️", "fifty_severity_debates", "Fifty Severity Debates", "Survive 50 incidents. Severity remains the longest task.", 50],
        ["📜", "certified_war_room_host", "Certified War Room Host", "Survive 70 incidents and mute the right participant.", 70],
        ["💯", "century_of_outages", "Century of Outages", "Survive 100 incidents. Availability rounds to 100%.", 100],
        ["🧭", "root_cause_tourist", "Root-Cause Tourist", "Survive 140 incidents without settling permanently.", 140],
        ["🏢", "incident_management_office", "Incident Management Office", "Survive 200 incidents. The PMO requests a template.", 200],
        ["🚒", "industrial_fire_watcher", "Industrial Fire Watcher", "Survive 280 incidents. Smoke is an observability signal.", 280],
        ["🏆", "four_hundred_critical_normals", "Four Hundred Critical Normals", "Survive 400 incidents marked both Critical and Normal.", 400],
        ["🛰️", "global_war_room", "Global War Room", "Survive 550 incidents across time zones and lunch.", 550],
        ["🌋", "seven_hundred_fifty_eruptions", "Seven Hundred Fifty Eruptions", "Survive 750 incidents. Production is geologically active.", 750],
        ["👑", "thousand_incident_commander", "Thousand-Incident Commander", "Survive 1,000 incidents. Your status is permanently amber.", 1000],
        ["♾️", "permanent_major_incident", "Permanent Major Incident", "Survive 1,500 incidents. The temporary bridge has tenure.", 1500],
      ],
    },
    {
      metric: "bugsSquashed",
      category: "operations",
      entries: [
        ["🐛", "first_bug_report", "First Bug Report", "Squash 1 roaming bug. Reproduction steps were excellent.", 1],
        ["🪲", "pair_debugging", "Pair Debugging", "Squash 2 bugs. One was observing the other.", 2],
        ["🩴", "approved_debugging_tool", "Approved Debugging Tool", "Squash 3 bugs using footwear from the standard catalog.", 3],
        ["🔍", "five_whys_one_bug", "Five Whys, One Bug", "Squash 5 bugs and blame requirements on why four.", 5],
        ["🧪", "quality_assurance_adjacent", "Quality Assurance Adjacent", "Squash 8 bugs after release.", 8],
        ["🧹", "backlog_exterminator", "Backlog Exterminator", "Squash 12 bugs. Product asks whether they were features.", 12],
        ["🛠️", "eighteen_hotfixes", "Eighteen Hotfixes", "Squash 18 bugs. The cold fix remains in review.", 18],
        ["🏅", "quarter_century_debugger", "Quarter-Century Debugger", "Squash 25 bugs. None reproduce locally.", 25],
        ["🕵️", "bug_private_investigator", "Bug Private Investigator", "Squash 35 bugs and follow the stack trace into management.", 35],
        ["🎖️", "fifty_feature_corrections", "Fifty Feature Corrections", "Squash 50 bugs after Marketing renames them.", 50],
        ["📜", "certified_bug_negotiator", "Certified Bug Negotiator", "Squash 70 bugs through constructive deletion.", 70],
        ["💯", "hundred_bug_release", "Hundred-Bug Release", "Squash 100 bugs. Release notes say minor stability improvements.", 100],
        ["🧬", "mutation_testing_subject", "Mutation Testing Subject", "Squash 150 bugs. Three evolve resistance.", 150],
        ["🧯", "production_pest_control", "Production Pest Control", "Squash 225 bugs during approved emergency windows.", 225],
        ["🏢", "bug_governance_board", "Bug Governance Board", "Squash 325 bugs and establish a bug steering committee.", 325],
        ["🏆", "four_hundred_seventy_five_fixes", "Four Hundred Seventy-Five Fixes", "Squash 475 bugs. Technical debt requests refinancing.", 475],
        ["🛰️", "distributed_bug_squasher", "Distributed Bug Squasher", "Squash 700 bugs across regions and repositories.", 700],
        ["👑", "thousand_bug_monarch", "Thousand-Bug Monarch", "Squash 1,000 bugs. The issue tracker grants diplomatic immunity.", 1000],
        ["🌌", "fifteen_hundred_edge_cases", "Fifteen Hundred Edge Cases", "Squash 1,500 bugs. The edge is now a circle.", 1500],
        ["♾️", "final_bug_final_v2", "Final Bug Final v2", "Squash 2,500 bugs. This one is definitely the last.", 2500],
      ],
    },
    {
      category: "operations",
      entries: [
        ["⚡", "first_temporary_fix", "First Temporary Fix", "Activate 1 operational boost. Temporary has no end date.", "buffsActivated", 1],
        ["☕", "three_coffee_architecture", "Three-Coffee Architecture", "Activate 3 boosts. Caffeine is now a dependency.", "buffsActivated", 3],
        ["🪄", "five_minutes_of_productivity", "Five Minutes of Productivity", "Activate 5 boosts before the calendar notices.", "buffsActivated", 5],
        ["🏅", "ten_operational_miracles", "Ten Operational Miracles", "Activate 10 boosts. Reliability remains faith-based.", "buffsActivated", 10],
        ["🔋", "twenty_borrowed_batteries", "Twenty Borrowed Batteries", "Activate 20 boosts. Return date is unknown.", "buffsActivated", 20],
        ["📜", "certified_boost_coordinator", "Certified Boost Coordinator", "Activate 35 boosts and schedule a boost retrospective.", "buffsActivated", 35],
        ["🚀", "fifty_temporary_accelerations", "Fifty Temporary Accelerations", "Activate 50 boosts. Baseline performance files a complaint.", "buffsActivated", 50],
        ["👑", "seventy_five_emergency_advantages", "Seventy-Five Emergency Advantages", "Activate 75 boosts. Emergency is now the operating model.", "buffsActivated", 75],
        ["📥", "inbox_zero_once", "Inbox Zero, Once", "Clear the queue 1 time. Take a screenshot; nobody will believe it.", "queueClears", 1],
        ["🌅", "three_quiet_mornings", "Three Quiet Mornings", "Clear the queue 3 times before the first meeting.", "queueClears", 3],
        ["🧘", "five_seconds_of_peace", "Five Seconds of Peace", "Clear the queue 5 times. Silence triggers monitoring.", "queueClears", 5],
        ["🏆", "ten_queue_victories", "Ten Queue Victories", "Clear the queue 10 times. It keeps respawning.", "queueClears", 10],
        ["🧹", "twenty_five_clean_inboxes", "Twenty-Five Clean Inboxes", "Clear the queue 25 times. Retention policy objects.", "queueClears", 25],
        ["🕊️", "fifty_ceasefires", "Fifty Ceasefires", "Clear the queue 50 times. Users honor none of them.", "queueClears", 50],
        ["🌡️", "hundred_ticket_fever", "Hundred-Ticket Fever", "Let the queue reach 100. Monitoring recommends hydration.", "maxOpenTickets", 100],
        ["🚧", "two_hundred_fifty_lane_closure", "Two-Hundred-Fifty Lane Closure", "Let the queue reach 250. Traffic management opens a ticket.", "maxOpenTickets", 250],
        ["🔥", "five_hundred_alarm_panel", "Five-Hundred Alarm Panel", "Let the queue reach 500. Every light is informative red.", "maxOpenTickets", 500],
        ["🌋", "thousand_ticket_eruption", "Thousand-Ticket Eruption", "Let the queue reach 1,000. Evacuation awaits CAB approval.", "maxOpenTickets", 1000],
        ["🌊", "five_thousand_ticket_flood", "Five-Thousand-Ticket Flood", "Let the queue reach 5,000. Sandbags are out of scope.", "maxOpenTickets", 5000],
        ["☄️", "twenty_five_thousand_impact", "Twenty-Five-Thousand Impact", "Let the queue reach 25,000. Business impact is now visible from space.", "maxOpenTickets", 25000],
      ],
    },
  ];

  const rankLabels = [
    "Orientation",
    "Probation",
    "Apprentice",
    "Certified",
    "Bronze",
    "Silver",
    "Gold",
    "Senior",
    "Lead",
    "Principal",
    "Distinguished",
    "Acting Manager",
    "Manager",
    "Director",
    "Senior Director",
    "Vice President",
    "Executive Sponsor",
    "Chief Officer",
    "Supreme Authority",
    "Post-Human",
  ];
  const rankEmojis = [
    "🪪",
    "📎",
    "🧾",
    "📜",
    "🥉",
    "🥈",
    "🥇",
    "🏅",
    "🎖️",
    "🏆",
    "⭐",
    "🧑‍💼",
    "💼",
    "🏛️",
    "🗿",
    "🚀",
    "🛰️",
    "👑",
    "🌌",
    "♾️",
  ];
  const rankNotes = [
    "Evidence is attached to a screenshot of the attachment.",
    "The mandatory training video buffers at 99%.",
    "Your mentor is an unmaintained wiki page.",
    "The certificate expires before the printer finishes.",
    "A bronze badge has been added to your email signature.",
    "Silver status includes priority access to the same queue.",
    "Gold status unlocks a premium escalation template.",
    "Senior responsibilities arrive without senior permissions.",
    "Leadership means forwarding the alert with urgency.",
    "The principal finding is that nobody owns it.",
    "Distinction was awarded by a panel currently offline.",
    "The acting role became permanent by calendar drift.",
    "Management requests a dashboard about the dashboard.",
    "The strategy is now a slide with three arrows.",
    "A steering committee has been formed to admire the problem.",
    "The title is global; the permissions remain local.",
    "Executive sponsorship consists of one thumbs-up reaction.",
    "The chief responsibility is knowing whom to blame.",
    "Policy now requires others to imitate your workaround.",
    "Human intervention has been marked as legacy.",
  ];
  const extendedTracks = [
    {
      id: "email_archaeology",
      title: "Email Archaeology",
      category: "tickets",
      metric: "resolved",
      thresholds: [5, 25, 75, 150, 500, 1500, 7500, 15000, 50000, 150000, 750000, 1500000, 7500000, 15000000, 75000000, 150000000, 750000000, 1500000000, 7500000000, 15000000000],
      action: (target) =>
        `Close ${target} tickets while searching for the attachment everyone definitely included.`,
    },
    {
      id: "duplicate_resurrection",
      title: "Duplicate Resurrection",
      category: "tickets",
      metric: "resolved",
      thresholds: [20, 100, 300, 750, 2500, 10000, 30000, 75000, 300000, 750000, 3000000, 7500000, 30000000, 75000000, 300000000, 750000000, 3000000000, 7500000000, 30000000000, 75000000000],
      action: (target) =>
        `Close ${target} tickets previously marked permanently resolved.`,
    },
    {
      id: "mouse_endurance",
      title: "Mouse Endurance Program",
      category: "clicking",
      metric: "manualClicks",
      thresholds: [5, 20, 40, 75, 150, 350, 750, 1500, 3500, 7500, 15000, 35000, 75000, 150000, 350000, 750000, 1500000, 3500000, 7500000, 15000000],
      action: (target) =>
        `Click ${target} times because the automation request needs a business case.`,
    },
    {
      id: "automation_governance",
      title: "Automation Governance Theatre",
      category: "automation",
      metric: "tps",
      thresholds: [0.5, 2, 10, 50, 250, 1000, 5000, 25000, 100000, 500000, 2500000, 10000000, 50000000, 250000000, 1000000000, 5000000000, 25000000000, 100000000000, 500000000000, 2500000000000],
      action: (target) =>
        `Reach ${target} tickets per second while governance reviews the script name.`,
    },
    {
      id: "executive_one_click",
      title: "Executive One-Click Authority",
      category: "clicking",
      metric: "clickPower",
      thresholds: [1.5, 3, 7, 15, 35, 75, 150, 350, 750, 1500, 3500, 7500, 15000, 35000, 75000, 150000, 350000, 750000, 1500000, 7500000],
      action: (target) =>
        `Resolve ${target} tickets per click using executive authority and one suspicious button.`,
    },
    {
      id: "asset_register_fiction",
      title: "Asset Register Fan Fiction",
      category: "procurement",
      metric: "upgradesOwned",
      thresholds: [2, 4, 7, 12, 20, 30, 50, 75, 100, 150, 210, 300, 400, 550, 700, 900, 1150, 1450, 1900, 3000],
      action: (target) =>
        `Own ${target} upgrades; the asset register knows about approximately seven.`,
    },
    {
      id: "vendor_safari",
      title: "Vendor Ecosystem Safari",
      category: "procurement",
      metric: "distinctUpgrades",
      thresholds: [1, 3, 5, 7, 9, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25, 28, 32, 38, 48, 58],
      action: (target) =>
        `Own ${target} different upgrades and call the resulting diagram an ecosystem.`,
    },
    {
      id: "budget_limbo",
      title: "Budget Limbo",
      category: "procurement",
      metric: "spent",
      thresholds: [50, 250, 1000, 5000, 25000, 100000, 500000, 2500000, 10000000, 50000000, 250000000, 1000000000, 5000000000, 25000000000, 100000000000, 500000000000, 2500000000000, 10000000000000, 50000000000000, 250000000000000],
      action: (target) =>
        `Spend ${target} tickets without using the word "overspend".`,
    },
    {
      id: "war_room_residency",
      title: "War Room Residency",
      category: "operations",
      metric: "incidentsTriggered",
      thresholds: [1, 4, 6, 10, 15, 22, 30, 42, 58, 80, 110, 150, 210, 290, 400, 550, 750, 1000, 1400, 2000],
      action: (target) =>
        `Survive ${target} incidents and remain on the bridge until someone says lessons learned.`,
    },
    {
      id: "bug_diplomacy",
      title: "Bug Diplomacy Corps",
      category: "operations",
      metric: "bugsSquashed",
      thresholds: [1, 4, 6, 10, 15, 22, 30, 42, 58, 80, 110, 150, 210, 290, 400, 550, 750, 1000, 1600, 3000],
      action: (target) =>
        `Squash ${target} bugs that passed all mandatory quality gates.`,
    },
    {
      id: "temporary_fix",
      title: "Temporary Fix Sustainability",
      category: "operations",
      metric: "buffsActivated",
      thresholds: [1, 2, 4, 7, 11, 16, 22, 30, 40, 52, 66, 82, 100, 122, 148, 178, 212, 250, 300, 400],
      action: (target) =>
        `Activate ${target} temporary boosts and extend each until the permanent fix arrives.`,
    },
    {
      id: "inbox_zero_wildlife",
      title: "Inbox Zero Wildlife Watch",
      category: "operations",
      metric: "queueClears",
      thresholds: [1, 2, 4, 7, 12, 18, 26, 36, 50, 68, 90, 118, 150, 190, 240, 300, 375, 460, 600, 1000],
      action: (target) =>
        `Clear the queue ${target} times; users coordinate the refill.`,
    },
    {
      id: "backlog_weather",
      title: "Backlog Weather Service",
      category: "operations",
      metric: "maxOpenTickets",
      thresholds: [50, 150, 350, 750, 1500, 3000, 6000, 10000, 18000, 30000, 50000, 80000, 120000, 180000, 260000, 380000, 550000, 800000, 1200000, 2000000],
      action: (target) =>
        `Let the queue reach ${target}; the dashboard uses a reassuring shade of red.`,
    },
    {
      id: "cron_appreciation",
      title: "Cron Appreciation Society",
      category: "automation",
      metric: "tps",
      thresholds: [3, 15, 75, 350, 1500, 7500, 35000, 150000, 750000, 3500000, 15000000, 75000000, 350000000, 1500000000, 7500000000, 35000000000, 150000000000, 750000000000, 3500000000000, 15000000000000],
      action: (target) =>
        `Reach ${target} tickets per second with a cron job documented as self-explanatory.`,
    },
    {
      id: "finops_storytelling",
      title: "FinOps Storytelling",
      category: "procurement",
      metric: "spent",
      thresholds: [75, 350, 1500, 7500, 35000, 150000, 750000, 3500000, 15000000, 75000000, 350000000, 1500000000, 7500000000, 35000000000, 150000000000, 750000000000, 3500000000000, 15000000000000, 75000000000000, 350000000000000],
      action: (target) =>
        `Spend ${target} tickets proving the cloud bill is technically optimized.`,
    },
  ];

  const formatTarget = (target) =>
    window.ticketClickerNumberUnits.formatInline(
      window.ticketClickerNumberUnits.formatParts(target),
    );

  const catalog = [];
  for (let tier = 0; tier < 20; tier += 1) {
    for (const achievementSeries of series) {
      const entry = achievementSeries.entries[tier];
      const [emoji, id, name, description, metricOrTarget, optionalTarget] = entry;
      catalog.push({
        id: `reputation_${id}`,
        emoji,
        name,
        description,
        category: achievementSeries.category,
        metric: optionalTarget === undefined ? achievementSeries.metric : metricOrTarget,
        target: optionalTarget === undefined ? metricOrTarget : optionalTarget,
      });
    }
  }

  const extendedCatalog = [];
  for (let tier = 0; tier < rankLabels.length; tier += 1) {
    for (const track of extendedTracks) {
      const target = track.thresholds[tier];
      extendedCatalog.push({
        id: `reputation_${track.id}_${tier + 1}`,
        emoji: rankEmojis[tier],
        name: `${track.title}: ${rankLabels[tier]}`,
        description: `${track.action(formatTarget(target))} ${rankNotes[tier]}`,
        category: track.category,
        metric: track.metric,
        target,
      });
    }
  }

  catalog.push(...extendedCatalog.slice(0, 492 - catalog.length));
  window.ticketClickerReputationCatalog = catalog;
})();
